"""empty message

Revision ID: 67c45e451739
Revises: 6fa514451b58
Create Date: 2023-04-26 00:36:39.865985

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67c45e451739'
down_revision = '6fa514451b58'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('userid', sa.String(length=150), nullable=False))
        batch_op.add_column(sa.Column('authority', sa.Integer(), nullable=False))
        batch_op.create_unique_constraint(None, ['userid'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('authority')
        batch_op.drop_column('userid')

    # ### end Alembic commands ###
