"""empty message

Revision ID: 99f824177a67
Revises: 4147efdd0147
Create Date: 2023-05-08 23:11:54.229832

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99f824177a67'
down_revision = '4147efdd0147'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('image', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('result', sa.LargeBinary(), nullable=True))
        batch_op.add_column(sa.Column('date', sa.DateTime(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('image', schema=None) as batch_op:
        batch_op.drop_column('date')
        batch_op.drop_column('result')
        batch_op.drop_column('user')

    # ### end Alembic commands ###
