"""empty message

Revision ID: c1d970b0f874
Revises: 6cbc995c95b7
Create Date: 2023-05-29 13:09:06.452737

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c1d970b0f874'
down_revision = '6cbc995c95b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('report',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user', sa.Integer(), nullable=False),
    sa.Column('image', sa.Integer(), nullable=False),
    sa.Column('content', sa.String(length=20000), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_report'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('report')
    # ### end Alembic commands ###
